
parameters:
    database_host: us-cdbr-iron-east-03.cleardb.net
    database_port: 3306
    database_name: heroku_e9780e2f9a922b8
    database_user: bb5b69c670a821
    database_password: 4bf57600
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: 2d77c4f071de0de84c8ccddd698c94ae07fd1eba
