app_home_index:
    path:     /
    defaults: { _controller: AppBundle:Home:index }
app_home_notif_wallpaper:
    path:     /notif/wallpaper.html
    defaults: { _controller: AppBundle:Home:notifWallpaper }
app_home_notif_url:
    path:     /notif/url.html
    defaults: { _controller: AppBundle:Home:notifUrl }
app_home_notif_user:
    path:     /notif/user.html
    defaults: { _controller: AppBundle:Home:notifUser }
app_home_notif_category:
    path:     /notif/category.html
    defaults: { _controller: AppBundle:Home:notifCategory }
api_home_api_device:
    path:   /api/device/{tkn}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Home:api_device }
app_support_index:
    path:     /support/index.html
    defaults: { _controller: AppBundle:Support:index }
app_support_view:
    path:     /support/view/{id}.html
    defaults: { _controller: AppBundle:Support:view }
app_support_delete:
    path:     /support/delete/{id}.html
    defaults: { _controller: AppBundle:Support:delete }
api_support_add:
    path:     /api/support/add/{token}/{purchase}/
    defaults: { _controller: AppBundle:Support:api_add }
    methods: POST
#report
app_report_index:
    path:     /report/index.html
    defaults: { _controller: AppBundle:Report:index }
app_report_delete:
    path:     /report/delete/{id}.html
    defaults: { _controller: AppBundle:Report:delete }
api_report_add:
    path:     /api/report/add/{token}/{purchase}/
    defaults: { _controller: AppBundle:Report:api_add }
    methods: POST
#slide
app_slide_add:
    path: /slide/add.html
    defaults: { _controller: AppBundle:Slide:add}
app_slide_index:
    path: /slide/index.html
    defaults: { _controller: AppBundle:Slide:index}
app_slide_edit:
    path: /slide/{id}.html
    defaults: { _controller: AppBundle:Slide:edit}
    requirements:
        id:  \d+
app_slide_delete:
    path: /slide/delete/{id}.html
    defaults: { _controller: AppBundle:Slide:delete}
    requirements:
        id:  \d+
app_slide_up:
    path: /slide/up/{id}.html
    defaults: { _controller: AppBundle:Slide:up}
    requirements:
        id:  \d+
app_slide_down:
    path: /slide/down/{id}.html
    defaults: { _controller: AppBundle:Slide:down}
    requirements:
        id:  \d+
api_slide_all:
    path:     /api/slide/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Slide:api_all }
#section 
app_section_add:
    path: /section/add.html
    defaults: { _controller: AppBundle:Section:add}
app_section_index:
    path: /section/index.html
    defaults: { _controller: AppBundle:Section:index}
app_section_edit:
    path: /section/edit/{id}.html
    defaults: { _controller: AppBundle:Section:edit}
    requirements:
        id:  \d+
app_section_delete:
    path: /section/delete/{id}.html
    defaults: { _controller: AppBundle:Section:delete}
    requirements:
        id:  \d+
app_section_up:
    path: /section/up/{id}.html
    defaults: { _controller: AppBundle:Section:up}
    requirements:
        id:  \d+
app_section_down:
    path: /section/down/{id}.html
    defaults: { _controller: AppBundle:Section:down}
    requirements:
        id:  \d+
app_section_view:
    path: /section/view/{id}.html
    defaults: { _controller: AppBundle:Section:view}
    requirements:
        id:  \d+
api_section_list:
    path:     /api/section/list/{token}/{purchase}/
    defaults: { _controller: AppBundle:Section:api_list }
    
#category 
app_category_add:
    path: /category/add.html
    defaults: { _controller: AppBundle:Category:add}
app_category_edit:
    path: /category/edit/{id}.html
    defaults: { _controller: AppBundle:Category:edit}
    requirements:
        id:  \d+
app_category_delete:
    path: /category/delete/{id}.html
    defaults: { _controller: AppBundle:Category:delete}
    requirements:
        id:  \d+
app_category_up:
    path: /category/up/{id}.html
    defaults: { _controller: AppBundle:Category:up}
    requirements:
        id:  \d+
app_category_down:
    path: /category/down/{id}.html
    defaults: { _controller: AppBundle:Category:down}
    requirements:
        id:  \d+
api_category_by:
    path:     /api/category/by/{id}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_by }
    requirements:
        id:  \d+  
api_category_by_section:
    path:     /api/category/list/{id}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_by_section }
    requirements:
        id:  \d+  
api_category_all:
    path: /api/category/all/{token}/{purchase}/
    defaults: { _controller: AppBundle:Category:api_all}
#version
app_version_add:
    path: /version/add.html
    defaults: { _controller: AppBundle:Version:add}
app_version_index:
    path: /version/index.html
    defaults: { _controller: AppBundle:Version:index}
app_version_edit:
    path: /version/edit/{id}.html
    defaults: { _controller: AppBundle:Version:edit}
    requirements:
        id:  \d+
app_version_delete:
    path: /version/delete/{id}.html
    defaults: { _controller: AppBundle:Version:delete}
    requirements:
        id:  \d+
api_version_check:
    path: /api/version/check/{code}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Version:api_check_v2}
    requirements:
        code:  \d+

#color 
app_color_add:
    path: /color/add.html
    defaults: { _controller: AppBundle:Color:add}
app_color_index:
    path: /color/index.html
    defaults: { _controller: AppBundle:Color:index}
app_color_edit:
    path: /color/edit/{id}.html
    defaults: { _controller: AppBundle:Color:edit}
    requirements:
        id:  \d+
app_color_delete:
    path: /color/delete/{id}.html
    defaults: { _controller: AppBundle:Color:delete}
    requirements:
        id:  \d+
app_color_up:
    path: /color/up/{id}.html
    defaults: { _controller: AppBundle:Color:up}
    requirements:
        id:  \d+
app_color_down:
    path: /color/down/{id}.html
    defaults: { _controller: AppBundle:Color:down}
    requirements:
        id:  \d+
api_color_list:
    path:     /api/color/list/{token}/{purchase}/
    defaults: { _controller: AppBundle:Color:api_list }
api_color_by:
    path:     /api/Color/by/{id}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Color:api_by }
    requirements:
        id:  \d+ 
#wallpaper 
app_wallpaper_multi:
    path: /wallpaper/multi.html
    defaults: { _controller: AppBundle:Wallpaper:multi}
app_wallpaper_add:
    path: /wallpaper/add.html
    defaults: { _controller: AppBundle:Wallpaper:add}
app_wallpaper_reviews:
    path: /wallpaper/reviews.html
    defaults: { _controller: AppBundle:Wallpaper:reviews}
app_wallpaper_index:
    path: /wallpaper/index.html
    defaults: { _controller: AppBundle:Wallpaper:index}
app_wallpaper_edit:
    path: /wallpaper/edit/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:edit}
    requirements:
        id:  \d+ 
app_wallpaper_review:
    path: /wallpaper/review/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:review}
    requirements:
        id:  \d+
app_wallpaper_view:
    path: /wallpaper/view/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:view}
    requirements:
        id:  \d+
app_wallpaper_delete:
    path: /wallpaper/delete/{id}.html
    defaults: { _controller: AppBundle:Wallpaper:delete}
    requirements:
        id:  \d+
api_wallpaper_all:
    path:     /api/wallpaper/all/{order}/{page}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_all }
    requirements:
        page: \d+
api_wallpaper_by_category:
    path:     /api/wallpaper/category/{page}/{category}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_category }
    requirements:
        page: \d+
        category: \d+
api_wallpaper_by_user:
    path:     /api/wallpaper/user/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_user }
    requirements:
        page: \d+
        user: \d+
api_wallpaper_by_me:
    path:     /api/wallpaper/me/{page}/{user}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_me }
    requirements:
        page: \d+
        user: \d+
api_wallpaper_by_color:
    path:     /api/wallpaper/color/{page}/{color}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_color }
    requirements:
        page: \d+
        color: \d+
api_wallpaper_by_query:
    path:     /api/wallpaper/query/{page}/{query}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_by_query }
    requirements:
        page: \d+
api_rate_add:
    path:     /api/rate/add/{user}/{wallpaper}/{value}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_rate }
api_rate_get:
    path:     /api/rate/get/{user}/{wallpaper}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_get_rate }
api_wallpaper_upload:
    path:     /api/wallpaper/upload/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_upload }
api_wallpaper_add_download:
    path:     /api/wallpaper/add/download/{token}/{purchase}/
    defaults: { _controller: AppBundle:Wallpaper:api_add_download }
    methods: POST
#comment
app_comment_delete:
    path:     /comment/delete/{id}.html
    defaults: { _controller: AppBundle:Comment:delete }
    requirements:
        id:  \d+
app_comment_delete_two:
    path:     /comment/delete_two/{id}.html
    defaults: { _controller: AppBundle:Comment:delete_two }
    requirements:
        id:  \d+
app_comment_hide:
    path:     /comment/hide/{id}.html
    defaults: { _controller: AppBundle:Comment:hide }
    requirements:
        id:  \d+
app_comment_hide_two:
    path:     /comment/hide_two/{id}.html
    defaults: { _controller: AppBundle:Comment:hide_two }
    requirements:
        id:  \d+  
app_comment_index:
    path:     /comment/index.html
    defaults: { _controller: AppBundle:Comment:index }
api_comment_add:
    path:     /api/comment/add/{token}/{purchase}/
    defaults: { _controller: AppBundle:Comment:api_add }
    methods: POST
api_comment_list:
    path:     /api/comment/list/{id}/{token}/{purchase}/
    defaults: { _controller: AppBundle:Comment:api_list }
    requirements:
        id:  \d+  